### ISSUE TITLE
Remove user-specific dev / run files

### ISSUE THREAD

**Issue by mlp6** [ian-hanus/SegDisplay#1]
There are some files / directories that should not be committed / shared with others who might use the plugin, including:
- `.idea/` (this is a user-specific configuration directory for PyCharm)
- `__pycache__/` this is a local cache python generates, that is very OS and package specific
- `*.pyc` like `__pycache__/`, this is a local, interpreted file that will cause conflicts on other systems.

You can remove this with `git rm` and if you want to keep you local copy, then `git rm --cached`.

**Comment by ian-hanus** [comment]
Fixed it, thanks!
